- hosts:
    - all
  tasks:
    - name: Copy files remote to remote
      copy:
       src: /tmp/semaphore/test.txt
       dest: /tmp/test.txt
       mode: '0644'
       remote_src: no
       
    - name: Exec python script
      script: /tmp/semaphore/test.py
