- hosts:
    - all
  tasks:
    - name: Copy files remote to remote
      copy:
       src: /tmp/semaphore/test.py
       dest: /tmp/test_v1.py
       mode: '0644'
       remote_src: no
       
    - name: Exec python script
        script: /tmp/test_v1.py
