- hosts:
    - all
  tasks:
    - name: Copy files remote to remote
      copy:
       src: /tmp/semaphore/test.py
       dest: /tmp/test_v1.py
       remote_src: no
       
    - name: Exec python script
      command: /tmp/test_v1.py
      
